import 'package:afrodite/src/extensions/text_style_extension.dart';
import 'package:flutter/material.dart';

class TokenTextTheme extends TextTheme {
  const TokenTextTheme({
    TextStyle? displayLarge,
    TextStyle? displayMedium,
    TextStyle? displaySmall,
    TextStyle? headlineLarge,
    TextStyle? headlineMedium,
    TextStyle? headlineSmall,
    TextStyle? titleLarge,
    TextStyle? titleMedium,
    TextStyle? titleSmall,
    TextStyle? bodyLarge,
    TextStyle? bodyMedium,
    TextStyle? bodySmall,
    TextStyle? labelLarge,
    TextStyle? labelMedium,
    TextStyle? labelSmall,
    TextStyle? headline1,
    TextStyle? headline2,
    TextStyle? headline3,
    TextStyle? headline4,
    TextStyle? headline5,
    TextStyle? headline6,
    TextStyle? subtitle1,
    TextStyle? subtitle2,
    TextStyle? bodyText1,
    TextStyle? bodyText2,
    TextStyle? caption,
    TextStyle? button,
    TextStyle? overline,
  }) : super(
            headline1: headline1,
            headline2: headline2,
            headline3: headline3,
            headline4: headline4,
            headline5: headline5,
            headline6: headline6,
            displaySmall: displaySmall,
            displayMedium: displayMedium,
            displayLarge: displayLarge,
            headlineSmall: headlineSmall,
            headlineMedium: headlineMedium,
            headlineLarge: headlineLarge,
            titleSmall: titleSmall,
            titleMedium: titleMedium,
            titleLarge: titleLarge,
            bodySmall: bodySmall,
            bodyMedium: bodyMedium,
            bodyLarge: bodyLarge,
            labelSmall: labelSmall,
            labelMedium: labelMedium,
            labelLarge: labelLarge,
            subtitle1: subtitle1,
            subtitle2: subtitle2,
            bodyText1: bodyText1,
            bodyText2: bodyText2,
            caption: caption,
            button: button,
            overline: overline);

  factory TokenTextTheme.fromJson(Map<String, dynamic> json) => TokenTextTheme(
        headline1: const TextStyle().fromJson(json['headline1']),
        headline2: const TextStyle().fromJson(json['headline2']),
        headline3: const TextStyle().fromJson(json['headline3']),
        headline4: const TextStyle().fromJson(json['headline4']),
        headline5: const TextStyle().fromJson(json['headline5']),
        headline6: const TextStyle().fromJson(json['headline6']),
        headlineSmall: const TextStyle().fromJson(json['headlineSmall']),
        headlineMedium: const TextStyle().fromJson(json['headlineMedium']),
        headlineLarge: const TextStyle().fromJson(json['headlineLarge']),
        titleSmall: const TextStyle().fromJson(json['titleSmall']),
        titleMedium: const TextStyle().fromJson(json['titleMedium']),
        titleLarge: const TextStyle().fromJson(json['titleLarge']),
        labelSmall: const TextStyle().fromJson(json['labelSmall']),
        labelMedium: const TextStyle().fromJson(json['labelMedium']),
        labelLarge: const TextStyle().fromJson(json['labelLarge']),
        displaySmall: const TextStyle().fromJson(json['displaySmall']),
        displayMedium: const TextStyle().fromJson(json['displayMedium']),
        displayLarge: const TextStyle().fromJson(json['displayLarge']),
        bodyText1: const TextStyle().fromJson(json['bodyText1']),
        bodyText2: const TextStyle().fromJson(json['bodyText2']),
        bodySmall: const TextStyle().fromJson(json['bodySmall']),
        bodyMedium: const TextStyle().fromJson(json['bodyMedium']),
        bodyLarge: const TextStyle().fromJson(json['bodyLarge']),
        subtitle1: const TextStyle().fromJson(json['subtitle1']),
        subtitle2: const TextStyle().fromJson(json['subtitle2']),
        caption: const TextStyle().fromJson(json['caption']),
        button: const TextStyle().fromJson(json['button']),
        overline: const TextStyle().fromJson(json['overline']),
      );
}
